---
title: "Intro To R - Overview"
author: "Ezra Herman"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document outlines the proposed sections and questions to be covered in the new intro to R workshop.

# Overview of RStudio

Questions:  
1. What are the four panels in RStudio?  
2. How is a project set up in RStudio?  
3. Where do we save files for RStudio to use?  


Objectives:  
1. Navigate the RStudio environment.   
2. Set up an RStudio project for the workshop.  
3. Save the workshop files from the vle into the project working directory.  

# Writing code in a script

Questions:  
1. What are the common terms used to describe R code?  
2. How can data be entered into RStudio manually?  
3. How are notes written alongside code?  
4. What is the structure of commands in R?  
5. How and why do we install packages?


Objectives:  
1. Define the following R terminology: object, assign, call, function, arguments and options.   
2. Assign values to a named vector using the `c()` function.   
3. Write comments to make a script easier to interpret.  
4. Use built-in functions and control their working with arguments and options.  
5. Install and load the `readr` package.

# Importing and viewing data

Questions:  
1. How is data from a .csv file imported into R?  
2. What are the differences between a `tibble` and a `data.frame`?  
3. How is a summary view of a `tibble` viewed in R?  
4. What is a factor variable in R? [*if there is time*]  
5. How are string variables converted to factor variables? [*if there is time*]  

Objectives:  
1. Use `read_csv()` to import data from a .csv file as a `tibble`.  
2. Describe the differences between a `tibble` and a `data.frame`.  
3. Use `head()`, `str()` and `summary()` to inspect a `tibble`.  
4. Describe the difference between a string variable and a factor variable. [*if there is time*]  
5. Use `factor()` to convert a string variable to a character variable. [*if there is time*]  

# Data wrangling

Questions:  
1. How can rows from a `tibble` be selected?  
2. How can columns from a `tibble` be selected?  
3. How can multiple data wrangling steps be combined into one command?  
4. How can new columns be created based on existing columns?  
5. How can group-specific summary statistics be obtained?  
6. How can a `tibble` be saved as a .csv file?

Objectives:  
1. Use `filter()` to select rows from a `tibble`.   
2. Use `select()` to select columns from a `tibble`.   
3. Use the pipe operator, `%>%`, to link commands together.  
4. Use `mutate()` to create new columns based on existing columns.  
5. Use `group_by()`, `summarise()`, `count()` and `mean()` to obtain group-specific summary statistics.   
6. Use `write_csv()` to save a `tibble` as a .csv file. 

# Plotting data with ggplot2

Questions:  
1. What is the general format of a `ggplot()` command?  
2. How can this format be adapted for scatterplots and boxplots?  
3. How are additional elements added to the plot, such as a title?  
4. How are multiple ggplot graphs grouped into one plotting region?  
5. How are ggplot objects exported from R?

Objectives:  
1. Describe the core components of a `ggplot()` command.  
2. Create scatterplots and boxplots with using the `ggplot2` package.  
3. Adjust `ggplot2` objects, for example by adding a title, with the help of Google.  
4. Use the `patchwork` package to group multiple `ggplot()` graphs together.  
5. Use `ggsave()` to export a ggplot plot. 
